// examples/vue/src/App.vue
<script setup lang="ts">
import "@glowhop/styles-tour/default.css";
// biome-ignore lint/correctness/noUnusedImports: used in template
import { createGlowTour, GlowTourDefault } from "@glowhop/vue-tour";

const tour = createGlowTour();
const workflow = tour
  .create("welcome")
  .step({ id: "welcome", target: "#welcome", title: "Welcome", content: "Hello world!" })
  .build();

// biome-ignore lint/correctness/noUnusedVariables: used in template
function start() {
  void tour.run(workflow);
}
</script>

<template>
  <div style="padding: 20px">
    <h1>GlowTour.js - Vue Example</h1>
    <button id="welcome" type="button" @click="start"
      style="padding: 10px 20px; font-size: 16px">
      Start tour
    </button>
  </div>
  <GlowTourDefault :tour="tour" />
</template>

// examples/angular/src/app.component.ts
import { Component } from "@angular/core";
import "@glowhop/styles-tour/default.css";
import { createGlowTour, GlowTourDefault } from "@glowhop/angular-tour";

@Component({
  standalone: true,
  imports: [GlowTourDefault],
  selector: "app-root",
  template: `
    <div style="padding: 20px">
      <h1>GlowTour.js - Angular Example</h1>
      <button
        id="welcome"
        type="button"
        (click)="start()"
        style="padding: 10px 20px; font-size: 16px"
      >
        Start tour
      </button>
    </div>
    <glow-tour-default [tour]="tour" />
  `,
})
export class AppComponent {
  readonly tour = createGlowTour();
  readonly workflow = this.tour
    .create("welcome")
    .step({ target: "#welcome", title: "Welcome", content: "Hello world!" })
    .build();

  start() {
    void this.tour.run(this.workflow);
  }
}
