// packages/solid/src/glow-tour.ts
import type {
  GlowTour as CoreGlowTour,
  StartOptions as CoreStartOptions,
  StepPropsStore as CoreStepPropsStore,
  TourState as CoreTourState,
  WorkflowDefinition as CoreWorkflowDefinition,
  GlowTourOptions,
} from "@glowhop/core-tour";
import { createGlowTour as createCoreGlowTour } from "@glowhop/core-tour";
import type { JSX } from "solid-js";

/** Solid content type: any valid Solid JSX element. */
export type SolidTourContent = JSX.Element;
/** Solid tour controller instance. */
export type Tour = CoreGlowTour<SolidTourContent>;
/** Solid tour state snapshot. */
export type TourState = CoreTourState<SolidTourContent>;
/** Solid step properties store. */
export type StepPropsStore = CoreStepPropsStore<SolidTourContent>;
/** Solid workflow definition. */
export type WorkflowDefinition = CoreWorkflowDefinition<SolidTourContent>;
/** Solid tour start options. */
export type StartOptions = CoreStartOptions<SolidTourContent>;

/**
 * Creates a new GlowTour.js instance for Solid.
 * @param options Tour options for error handling.
 * @returns A tour controller ready to run Solid workflows.
 */
export function createGlowTour(options: GlowTourOptions = {}): Tour {
  return createCoreGlowTour<SolidTourContent>(options);
}

// packages/react/src/glow-tour.ts
import type {
  GlowTour as CoreGlowTour,
  StartOptions as CoreStartOptions,
  StepPropsStore as CoreStepPropsStore,
  TourState as CoreTourState,
  WorkflowDefinition as CoreWorkflowDefinition,
  GlowTourOptions,
} from "@glowhop/core-tour";
import { createGlowTour as createCoreGlowTour } from "@glowhop/core-tour";
import type { ReactNode } from "react";

/** React content type: any valid React node. */
export type ReactTourContent = ReactNode;
/** React tour controller instance. */
export type Tour = CoreGlowTour<ReactTourContent>;
/** React tour state snapshot. */
export type TourState = CoreTourState<ReactTourContent>;
/** React step properties store. */
export type StepPropsStore = CoreStepPropsStore<ReactTourContent>;
/** React workflow definition. */
export type WorkflowDefinition = CoreWorkflowDefinition<ReactTourContent>;
/** React tour start options. */
export type StartOptions = CoreStartOptions<ReactTourContent>;

/**
 * Creates a new GlowTour.js instance for React.
 * @param options Tour options for error handling.
 * @returns A tour controller ready to run React workflows.
 */
export function createGlowTour(options: GlowTourOptions = {}): Tour {
  return createCoreGlowTour<ReactTourContent>(options);
}
