// packages/solid/src/use-glow-tour.ts
import type { GlowTourOptions } from "@glowhop/core-tour";
import { type Accessor, onCleanup } from "solid-js";
import { useTourSnapshot } from "./components/tour-components";
import { createGlowTour, type Tour, type TourState } from "./glow-tour";

/** What `useGlowTour` returns: the tour, its methods, and one accessor per state field. */
export type UseGlowTourResult = Pick<
  Tour,
  "advance" | "cancel" | "create" | "goTo" | "hidePopover" | "previous" | "showPopover" | "start"
> & {
  /** The tour instance, to pass to `GlowTourDefault` or `GlowTourRoot`. */
  readonly tour: Tour;
} & { readonly [K in keyof TourState]: Accessor<TourState[K]> };

/**
 * Runs a tour from a component, with its state as accessors.
 *
 * Called with options, it creates a tour and disposes it when the owning scope is cleaned up.
 * Called with an existing tour, it only reads it and never disposes it.
 * @param source Options for a new tour, or an existing tour to share.
 * @returns The tour, its methods, and one accessor per state field.
 */
export function useGlowTour(source: GlowTourOptions | Tour = {}): UseGlowTourResult {
  const shared = "start" in source;
  const tour = shared ? source : createGlowTour(source);
  if (!shared) onCleanup(tour.dispose);
  const snapshot = useTourSnapshot(() => tour);
  const { advance, cancel, create, goTo, hidePopover, previous, showPopover, start } = tour;
  const result: Record<string, unknown> = {
    advance,
    cancel,
    create,
    goTo,
    hidePopover,
    previous,
    showPopover,
    start,
    tour,
  };
  for (const key of Object.keys(snapshot()) as (keyof TourState)[]) {
    result[key] = () => snapshot()[key];
  }
  return result as UseGlowTourResult;
}

// packages/react/src/use-glow-tour.ts
import type { GlowTourOptions } from "@glowhop/core-tour";
import { useState } from "react";
import { useTourSnapshot } from "./components/tour-components";
import { createGlowTour, type Tour, type TourState } from "./glow-tour";

/** What `useGlowTour` returns: the tour, its methods, and its current state fields. */
export type UseGlowTourResult = Pick<
  Tour,
  "advance" | "cancel" | "create" | "goTo" | "hidePopover" | "previous" | "showPopover" | "start"
> &
  TourState & {
    /** The tour instance, to pass to `GlowTourDefault` or `GlowTourRoot`. */
    readonly tour: Tour;
  };

/**
 * Runs a tour from a component and re-renders when its state changes.
 *
 * Called with options, it creates a tour once, on the first render. That tour is released with
 * its root when the component unmounts: call `tour.dispose()` yourself to end it earlier.
 * Called with an existing tour, it only reads it.
 * @param source Options for a new tour, or an existing tour to share.
 * @returns The tour, its methods, and its current state fields.
 */
export function useGlowTour(source: GlowTourOptions | Tour = {}): UseGlowTourResult {
  const [owned] = useState(() => ("start" in source ? null : createGlowTour(source)));
  const tour = owned ?? (source as Tour);
  const { advance, cancel, create, goTo, hidePopover, previous, showPopover, start } = tour;
  return {
    ...useTourSnapshot(tour),
    advance,
    cancel,
    create,
    goTo,
    hidePopover,
    previous,
    showPopover,
    start,
    tour,
  };
}
