// packages/angular/src/lib/components/default-tour.ts
import { Component, Input } from "@angular/core";
import type { GlowTour } from "@glowhop/core-tour";
import type { AngularTourContent } from "../glow-tour";
import {
  GlowTourAdvanceTrigger,
  GlowTourCancelTrigger,
  GlowTourContent,
  GlowTourFooter,
  GlowTourHeader,
  GlowTourOverlay,
  GlowTourPointer,
  GlowTourPopover,
  GlowTourPreviousTrigger,
  GlowTourRoot,
} from "./tour-components";

@Component({
  selector: "glow-tour-default",
  standalone: true,
  imports: [
    GlowTourRoot,
    GlowTourOverlay,
    GlowTourPointer,
    GlowTourPopover,
    GlowTourHeader,
    GlowTourContent,
    GlowTourFooter,
    GlowTourCancelTrigger,
    GlowTourPreviousTrigger,
    GlowTourAdvanceTrigger,
  ],
  template: `
    <glow-tour-root [tour]="tour" [idPrefix]="idPrefix">
      <glow-tour-overlay />
      <glow-tour-pointer />
      <glow-tour-popover>
        <glow-tour-header />
        <glow-tour-content />
        <glow-tour-footer>
          <glow-tour-cancel-trigger />
          <glow-tour-previous-trigger />
          <glow-tour-advance-trigger />
        </glow-tour-footer>
      </glow-tour-popover>
    </glow-tour-root>
  `,
})
/** Default GlowTour.js component that renders all tour UI elements in a standard layout. */
export class GlowTourDefault {
  /** The tour controller instance to display. */
  @Input({ required: true }) tour!: GlowTour<AngularTourContent>;
  /** Optional prefix for generated HTML IDs. */
  @Input() idPrefix?: string;
}

// packages/react/src/components/default-tour.tsx
import type { GlowTour as CoreGlowTour } from "@glowhop/core-tour";
import type { ReactTourContent } from "../glow-tour";
import {
  GlowTourAdvanceTrigger,
  GlowTourCancelTrigger,
  GlowTourContent,
  GlowTourFooter,
  GlowTourHeader,
  GlowTourOverlay,
  GlowTourPointer,
  GlowTourPopover,
  GlowTourPreviousTrigger,
  GlowTourRoot,
} from "./tour-components";

/** Props for the GlowTourDefault component. */
export interface GlowTourDefaultProps {
  /** Optional prefix for internal element IDs. */
  readonly idPrefix?: string;
  /** The tour controller instance. */
  readonly tour: CoreGlowTour<ReactTourContent>;
}

/**
 * A default tour UI component that includes overlay, pointer, popover with header, content, and footer.
 * Provides all standard tour controls (previous, advance, cancel buttons).
 * @param props The component props.
 * @returns The rendered tour UI.
 */
export function GlowTourDefault({ idPrefix, tour }: GlowTourDefaultProps) {
  return (
    <GlowTourRoot idPrefix={idPrefix} tour={tour}>
      <GlowTourOverlay />
      <GlowTourPointer />
      <GlowTourPopover>
        <GlowTourHeader />
        <GlowTourContent />
        <GlowTourFooter>
          <GlowTourCancelTrigger />
          <GlowTourPreviousTrigger />
          <GlowTourAdvanceTrigger />
        </GlowTourFooter>
      </GlowTourPopover>
    </GlowTourRoot>
  );
}
