// packages/solid/src/components/tour-components.ts
import type {
  ClassValue,
  GlowTour as CoreGlowTour,
  TourClassNames,
  TourState,
} from "@glowhop/core-tour";
import {
  type AdapterRootBinding,
  connectGlowTourRoot,
  OVERLAY_IDLE_ATTRIBUTES,
  OVERLAY_IDLE_STYLE,
  OVERLAY_PATH_IDLE_ATTRIBUTES,
  POINTER_IDLE_ATTRIBUTES,
  POINTER_IDLE_STYLE,
  POPOVER_IDLE_ATTRIBUTES,
  POPOVER_IDLE_STYLE,
} from "@glowhop/core-tour/adapter";
import {
  type Accessor,
  createComponent,
  createContext,
  createEffect,
  createSignal,
  type JSX,
  mergeProps,
  onCleanup,
  type ParentProps,
  Show,
  splitProps,
  useContext,
} from "solid-js";
import { Dynamic } from "solid-js/web";
import type { SolidTourContent } from "../glow-tour";

type Tour = CoreGlowTour<SolidTourContent>;
type RootProps = ParentProps<
  Omit<JSX.HTMLAttributes<HTMLDivElement>, "id" | "ref"> & {
    idPrefix?: string;
    tour: Tour;
  }
>;
type ElementProps = ParentProps<Omit<JSX.HTMLAttributes<HTMLElement>, "id" | "ref">>;
type ContentProps = Omit<JSX.HTMLAttributes<HTMLElement>, "children" | "id">;
type OverlayProps = ParentProps<Omit<JSX.SvgSVGAttributes<SVGSVGElement>, "ref">>;
/** Content displayed in the pointer indicator for each direction. */
export interface PointerDirectionContent {
  readonly top?: JSX.Element;
  readonly bottom?: JSX.Element;
  readonly left?: JSX.Element;
  readonly right?: JSX.Element;
}

const DEFAULT_POINTER_DIRECTION_CONTENT: Required<PointerDirectionContent> = {
  bottom: "👇",
  left: "👈",
  right: "👉",
  top: "👆",
};

type PointerProps = Omit<JSX.HTMLAttributes<HTMLElement>, "aria-hidden" | "children" | "ref"> & {
  directionContent?: PointerDirectionContent;
};
type ButtonProps = Omit<JSX.ButtonHTMLAttributes<HTMLButtonElement>, "children" | "type"> & {
  children?: (props: JSX.ButtonHTMLAttributes<HTMLButtonElement>) => JSX.Element;
  disabled?: boolean;
};
type PreviousTriggerProps = ButtonProps & { previousLabel?: string };
type AdvanceTriggerProps = ButtonProps & { finishLabel?: string; advanceLabel?: string };
type CancelTriggerProps = ButtonProps & { cancelLabel?: string };
type ButtonClickEvent = MouseEvent & { currentTarget: HTMLButtonElement; target: Element };

interface TourContextValue {
  readonly binding: () => AdapterRootBinding | null;
  readonly tour: () => Tour;
}

const TourContext = createContext<TourContextValue>();

function useTourScope() {
  const context = useContext(TourContext);
  if (!context) {
    throw new Error("GlowTour components must be rendered inside <GlowTourRoot tour={...}>.");
  }
  return context;
}

/** @internal Reactive snapshot of a tour's state, shared with `useGlowTour`. */
export function useTourSnapshot(tour: () => Tour) {
  const [snapshot, setSnapshot] = createSignal<TourState<SolidTourContent>>(tour().state.get());
  createEffect(() => {
    const activeTour = tour();
    setSnapshot(activeTour.state.get());
    const unsubscribe = activeTour.state.subscribe(setSnapshot);
    onCleanup(unsubscribe);
  });
  return snapshot;
}

/**
 * Reads the state of the tour rendered by the enclosing `<GlowTourRoot>`.
 *
 * Use it to build tour UI inside the root; use `useGlowTour` to run a tour from a component.
 * @returns The current tour state.
 */
export function useGlowTourContext(): Accessor<TourState<SolidTourContent>> {
  return useTourSnapshot(useTourScope().tour);
}

function useBoundElement<T extends Element>(
  bind: (binding: AdapterRootBinding, element: T) => () => void,
) {
  const context = useTourScope();
  const [element, setElement] = createSignal<T | null>(null);
  createEffect(() => {
    const activeBinding = context.binding();
    const activeElement = element();
    if (!activeBinding || !activeElement) return;
    return bind(activeBinding, activeElement);
  });
  return setElement;
}

function currentStep(snapshot: TourState<SolidTourContent>) {
  return snapshot.currentStep?.currentProps ?? null;
}

/** Joins the component's own classes with the ones the current step adds to it. */
function joinClassNames(...values: (ClassValue | undefined)[]) {
  return values.flat().filter(Boolean).join(" ") || undefined;
}

/** Reads the component's `class` followed by the current step's `classNames[slot]`. */
function stepClass(
  snapshot: Accessor<TourState<SolidTourContent>>,
  slot: keyof TourClassNames,
  className: string | undefined,
) {
  return joinClassNames(className, currentStep(snapshot())?.classNames?.[slot]);
}

/**
 * Root component that must wrap all other tour components.
 *
 * Manages tour initialization and connects the tour instance to the DOM.
 * All other tour components (GlowTourOverlay, GlowTourPointer, GlowTourPopover, etc.) must be rendered inside this root.
 * @param props Component props including the tour instance and optional ID prefix.
 * @returns The root provider component.
 */
export function GlowTourRoot(props: RootProps): JSX.Element {
  const [local, other] = splitProps(props, ["children", "idPrefix", "tour"]);
  const [element, setElement] = createSignal<HTMLElement | null>(null);
  const [binding, setBinding] = createSignal<AdapterRootBinding | null>(null);

  createEffect(() => {
    const root = element();
    const tour = local.tour;
    const idPrefix = local.idPrefix;
    if (!root) return;
    const lease = connectGlowTourRoot(tour, {
      idPrefix,
      root,
    });
    setBinding(lease);
    onCleanup(() => {
      lease.release();
      setBinding((active) => (active === lease ? null : active));
    });
  });

  return createComponent(TourContext.Provider, {
    value: {
      binding,
      tour() {
        return local.tour;
      },
    },
    get children() {
      return createComponent(
        Dynamic,
        mergeProps(other, {
          component: "div",
          "data-glow-tour-root": "",
          ref: setElement,
          get children() {
            return local.children;
          },
        }),
      );
    },
  });
}

/**
 * The popover container that displays step content.
 *
 * Renders as a `<section>`.
 * Should contain GlowTourHeader, GlowTourContent, and GlowTourFooter components.
 * @param props HTML attributes and children.
 * @returns The popover container.
 */
export function GlowTourPopover(props: ElementProps): JSX.Element {
  const context = useTourScope();
  const snapshot = useTourSnapshot(context.tour);
  // Without a title, the content names the dialog instead of describing it.
  const titled = () => {
    const step = currentStep(snapshot());
    return !step || step.title != null;
  };
  const [local, other] = splitProps(props, ["children"]);
  const ref = useBoundElement<HTMLElement>((binding, element) => binding.bindPopover(element));

  return createComponent(
    Dynamic,
    mergeProps(other, {
      get "aria-describedby"() {
        return titled() ? context.binding()?.ids.description : undefined;
      },
      "aria-hidden": POPOVER_IDLE_ATTRIBUTES["aria-hidden"],
      get "aria-labelledby"() {
        const ids = context.binding()?.ids;
        return titled() ? ids?.title : ids?.description;
      },
      get class() {
        return stepClass(snapshot, "popover", other.class);
      },
      component: "section",
      "data-glow-tour-popover": "",
      get id() {
        return context.binding()?.ids.popover;
      },
      inert: POPOVER_IDLE_ATTRIBUTES.inert,
      ref,
      role: "dialog",
      get style() {
        return other.style ?? POPOVER_IDLE_STYLE;
      },
      tabIndex: -1,
      get children() {
        return local.children;
      },
    }),
  );
}

/**
 * Displays the title of the current step.
 * @param props HTML attributes.
 * @returns The step title header.
 */
export function GlowTourHeader(props: ContentProps): JSX.Element {
  const context = useTourScope();
  const snapshot = useTourSnapshot(context.tour);
  return Show({
    get when() {
      const step = currentStep(snapshot());
      return !step || step.title != null;
    },
    get children() {
      return createComponent(
        Dynamic,
        mergeProps(props, {
          get class() {
            return stepClass(snapshot, "header", props.class);
          },
          component: "header",
          "data-glow-tour-header": "",
          get id() {
            return context.binding()?.ids.title;
          },
          get children() {
            return currentStep(snapshot())?.title ?? null;
          },
        }),
      );
    },
  });
}

/**
 * Displays the body content of the current step.
 * @param props HTML attributes.
 * @returns The step content area.
 */
export function GlowTourContent(props: ContentProps): JSX.Element {
  const context = useTourScope();
  const snapshot = useTourSnapshot(context.tour);
  return createComponent(
    Dynamic,
    mergeProps(props, {
      "aria-live": "polite",
      get class() {
        return stepClass(snapshot, "content", props.class);
      },
      component: "div",
      "data-glow-tour-content": "",
      get id() {
        return context.binding()?.ids.description;
      },
      get children() {
        return currentStep(snapshot())?.content ?? null;
      },
    }),
  );
}

/**
 * The footer section of the popover, typically containing navigation buttons.
 * @param props HTML attributes and children.
 * @returns The footer container.
 */
export function GlowTourFooter(props: ElementProps): JSX.Element {
  const snapshot = useTourSnapshot(useTourScope().tour);
  return createComponent(
    Dynamic,
    mergeProps(props, {
      get class() {
        return stepClass(snapshot, "footer", props.class);
      },
      component: "footer",
      "data-glow-tour-footer": "",
    }),
  );
}

/**
 * The dimmed overlay backdrop that highlights the target element.
 * Renders as an SVG with a cutout around the target.
 * @param props SVG attributes.
 * @returns The overlay SVG element.
 */
export function GlowTourOverlay(props: OverlayProps): JSX.Element {
  const [local, other] = splitProps(props, ["children", "viewBox"]);
  const snapshot = useTourSnapshot(useTourScope().tour);
  const ref = useBoundElement<SVGSVGElement>((binding, element) => binding.bindOverlay(element));
  const path = createComponent(Dynamic, {
    component: "path",
    cursor: OVERLAY_PATH_IDLE_ATTRIBUTES.cursor,
    "data-glow-tour-overlay-path": "",
    "fill-rule": "evenodd",
    opacity: OVERLAY_PATH_IDLE_ATTRIBUTES.opacity,
    "pointer-events": OVERLAY_PATH_IDLE_ATTRIBUTES["pointer-events"],
  });

  return createComponent(
    Dynamic,
    mergeProps(other, {
      "aria-hidden": true,
      get class() {
        return stepClass(snapshot, "overlay", other.class);
      },
      component: "svg",
      "data-glow-tour-allow-interaction":
        OVERLAY_IDLE_ATTRIBUTES["data-glow-tour-allow-interaction"],
      "data-glow-tour-overlay": "",
      focusable: "false",
      inert: OVERLAY_IDLE_ATTRIBUTES.inert,
      preserveAspectRatio: OVERLAY_IDLE_ATTRIBUTES.preserveAspectRatio,
      ref,
      role: "presentation",
      get style() {
        return other.style ?? OVERLAY_IDLE_STYLE;
      },
      get viewBox() {
        return local.viewBox ?? "0 0 0 0";
      },
      get children() {
        return [path, local.children];
      },
    }),
  );
}

/**
 * A pointer/indicator that visually highlights the target element.
 * Displays directional content (emoji or custom content) based on pointer position.
 * Renders as a `<div>`.
 * @param props HTML attributes and `directionContent`.
 * @returns The pointer indicator element.
 */
export function GlowTourPointer(props: PointerProps): JSX.Element {
  const [local, other] = splitProps(props, ["directionContent"]);
  const snapshot = useTourSnapshot(useTourScope().tour);
  const ref = useBoundElement<HTMLElement>((binding, element) => binding.bindPointer(element));
  const directions = (
    Object.keys(DEFAULT_POINTER_DIRECTION_CONTENT) as Array<keyof PointerDirectionContent>
  ).map((direction) =>
    createComponent(Dynamic, {
      component: "div",
      "data-glow-tour-pointer-direction": direction,
      get children() {
        return local.directionContent?.[direction] ?? DEFAULT_POINTER_DIRECTION_CONTENT[direction];
      },
    }),
  );

  return createComponent(
    Dynamic,
    mergeProps(other, {
      "aria-hidden": POINTER_IDLE_ATTRIBUTES["aria-hidden"],
      get class() {
        return stepClass(snapshot, "pointer", other.class);
      },
      component: "div",
      "data-glow-tour-pointer": "",
      ref,
      get style() {
        return other.style ?? POINTER_IDLE_STYLE;
      },
      children: directions,
    }),
  );
}

function Trigger(
  props: ButtonProps & {
    capabilityDisabled: boolean;
    label: string;
    marker: "cancel" | "advance" | "previous";
  },
): JSX.Element {
  const context = useTourScope();
  const [local, other] = splitProps(props, ["children", "capabilityDisabled", "label", "marker"]);
  const buttonProps = mergeProps(other, {
    get "aria-controls"() {
      return context.binding()?.ids.popover;
    },
    get "aria-label"() {
      return other["aria-label"] || local.label;
    },
    get "aria-disabled"() {
      return local.capabilityDisabled || other.disabled === true;
    },
    get "data-glow-tour-cancel-trigger"() {
      return local.marker === "cancel" ? true : undefined;
    },
    get "data-glow-tour-consumer-disabled"() {
      return other.disabled === true ? "true" : undefined;
    },
    get "data-glow-tour-advance-trigger"() {
      return local.marker === "advance" ? true : undefined;
    },
    get "data-glow-tour-previous-trigger"() {
      return local.marker === "previous" ? true : undefined;
    },
    get disabled() {
      return local.capabilityDisabled || other.disabled === true;
    },
    onClick(event: ButtonClickEvent) {
      if (typeof other.onClick === "function") other.onClick(event);
    },
    type: "button" as const,
  });

  if (local.children) return local.children(buttonProps);
  return createComponent(
    Dynamic,
    mergeProps(buttonProps, {
      component: "button",
      get children() {
        return local.label;
      },
    }),
  );
}

/**
 * Button that navigates to the previous step.
 * Automatically disabled based on tour state.
 * @param props Button props and an optional `previousLabel` for the button text.
 * @returns The back button.
 */
export function GlowTourPreviousTrigger(props: PreviousTriggerProps): JSX.Element {
  const context = useTourScope();
  const snapshot = useTourSnapshot(context.tour);
  return Trigger(
    mergeProps(props, {
      // Tour state disables a trigger only while the tour is active: disabling it natively outside
      // of that, as a replacing start does, would blur the focused trigger.
      get capabilityDisabled() {
        return (
          (snapshot().status === "active" && !snapshot().canPrevious) ||
          currentStep(snapshot())?.controls?.previous?.state === "disabled"
        );
      },
      label: props.previousLabel ?? "Previous step",
      get class() {
        return stepClass(snapshot, "previous", props.class);
      },
      marker: "previous" as const,
    }),
  );
}

/**
 * Button that navigates to the next step, or finishes the tour on the last step.
 * Automatically disabled based on tour state.
 * @param props Button props, an optional `advanceLabel` for non-final steps, and `finishLabel` for the final step.
 * @returns The advance button.
 */
export function GlowTourAdvanceTrigger(props: AdvanceTriggerProps): JSX.Element {
  const context = useTourScope();
  const snapshot = useTourSnapshot(context.tour);
  return Trigger(
    mergeProps(props, {
      get capabilityDisabled() {
        return (
          (snapshot().status === "active" && !snapshot().canAdvance) ||
          currentStep(snapshot())?.controls?.advance?.state === "disabled"
        );
      },
      get label() {
        return snapshot().isLastStep
          ? (props.finishLabel ?? "Finish tour")
          : (props.advanceLabel ?? "Advance step");
      },
      get class() {
        return stepClass(snapshot, "advance", props.class);
      },
      marker: "advance" as const,
    }),
  );
}

/**
 * Button that cancels the tour.
 * Automatically disabled based on tour state.
 * @param props Button props and an optional `cancelLabel` for the button text.
 * @returns The cancel button.
 */
export function GlowTourCancelTrigger(props: CancelTriggerProps): JSX.Element {
  const context = useTourScope();
  const snapshot = useTourSnapshot(context.tour);
  return Trigger(
    mergeProps(props, {
      get capabilityDisabled() {
        return (
          (snapshot().status === "active" && !snapshot().canCancel) ||
          currentStep(snapshot())?.controls?.cancel?.state === "disabled"
        );
      },
      get label() {
        return props.cancelLabel ?? "Skip";
      },
      get class() {
        return stepClass(snapshot, "cancel", props.class);
      },
      marker: "cancel" as const,
    }),
  );
}

// packages/angular/src/lib/components/tour-components.ts
import { NgTemplateOutlet } from "@angular/common";
import {
  booleanAttribute,
  Component,
  computed,
  DestroyRef,
  Directive,
  ElementRef,
  effect,
  Injectable,
  InjectionToken,
  Injector,
  Input,
  inject,
  type OnChanges,
  type OnDestroy,
  type OnInit,
  type Signal,
  signal,
  TemplateRef,
  ViewChild,
} from "@angular/core";
import type { GlowTour as CoreGlowTour, TourClassNames, TourState } from "@glowhop/core-tour";
import {
  type AdapterRootBinding,
  connectGlowTourRoot,
  OVERLAY_IDLE_ATTRIBUTES,
  OVERLAY_IDLE_STYLE,
  OVERLAY_PATH_IDLE_ATTRIBUTES,
  POINTER_IDLE_ATTRIBUTES,
  POINTER_IDLE_STYLE,
  POPOVER_IDLE_ATTRIBUTES,
  POPOVER_IDLE_STYLE,
  styleRecordToCssText,
} from "@glowhop/core-tour/adapter";
import type { AngularTourContent } from "../glow-tour";

/** The classes the current step adds to the `slot` component, as one class string. */
function joinStepClass(state: TourState<AngularTourContent> | null, slot: keyof TourClassNames) {
  return [state?.currentStep?.currentProps.classNames?.[slot] ?? []].flat().join(" ");
}

const OVERLAY_IDLE_STYLE_TEXT = styleRecordToCssText(OVERLAY_IDLE_STYLE);
const POINTER_IDLE_STYLE_TEXT = styleRecordToCssText(POINTER_IDLE_STYLE);
const POPOVER_IDLE_STYLE_TEXT = styleRecordToCssText(POPOVER_IDLE_STYLE);

type Tour = CoreGlowTour<AngularTourContent>;

/** Pointer direction content value type: string or TemplateRef. */
export type PointerDirectionValue = string | TemplateRef<unknown>;

/** Pointer direction content configuration for custom pointer content. */
export interface PointerDirectionContent {
  readonly top?: PointerDirectionValue;
  readonly bottom?: PointerDirectionValue;
  readonly left?: PointerDirectionValue;
  readonly right?: PointerDirectionValue;
}

const DEFAULT_POINTER_DIRECTION_CONTENT: Required<PointerDirectionContent> = {
  bottom: "👇",
  left: "👈",
  right: "👉",
  top: "👆",
};

const POINTER_DIRECTIONS = ["top", "bottom", "left", "right"] as const;

interface ActiveRootBinding {
  readonly binding: AdapterRootBinding;
  readonly idPrefix: string | undefined;
  readonly root: HTMLElement;
  readonly tour: Tour;
}

@Injectable()
class GlowTourScope {
  readonly binding = signal<AdapterRootBinding | null>(null);
  readonly tour = signal<Tour | null>(null);
  private readonly snapshot = signal<TourState<AngularTourContent> | null>(null);
  readonly state = this.snapshot.asReadonly();

  constructor() {
    effect(
      (onCleanup) => {
        const tour = this.tour();
        if (!tour) {
          this.snapshot.set(null);
          return;
        }
        this.snapshot.set(tour.state.get());
        onCleanup(tour.state.subscribe((state) => this.snapshot.set(state)));
      },
      { allowSignalWrites: true },
    );
  }
}

const GLOW_TOUR_SCOPE = new InjectionToken<GlowTourScope>("GlowTourScope");

function useTourScope() {
  const scope = inject(GLOW_TOUR_SCOPE, { optional: true });
  if (!scope) {
    throw new Error('GlowTour components must be rendered inside <glow-tour-root [tour]="...">.');
  }
  return scope;
}

/**
 * Reads the state of the tour rendered by the enclosing `glow-tour-root`.
 * Use it to build tour UI inside the root; use `injectGlowTour` to run a tour from a component.
 * @returns A signal containing the current tour state or null.
 */
export function injectGlowTourContext(): Signal<TourState<AngularTourContent> | null> {
  return useTourScope().state;
}

@Directive()
export abstract class GlowTourReactiveComponent {
  protected readonly scope = useTourScope();
  protected readonly snapshot = this.scope.state;
  protected readonly step = computed(() => this.snapshot()?.currentStep?.currentProps ?? null);
  /** The classes the current step adds to the `slot` component. */
  protected stepClass(slot: keyof TourClassNames) {
    return joinStepClass(this.snapshot(), slot);
  }
}

@Component({
  selector: "glow-tour-root",
  standalone: true,
  host: { "data-glow-tour-root": "" },
  providers: [GlowTourScope, { provide: GLOW_TOUR_SCOPE, useExisting: GlowTourScope }],
  template: "<ng-content />",
})
/** Root container component for GlowTour.js. Provides tour context and manages the root binding. */
export class GlowTourRoot implements OnChanges, OnDestroy, OnInit {
  /** The tour controller instance to display. */
  @Input({ required: true }) tour!: Tour;
  /** Optional prefix for generated HTML IDs. */
  @Input() idPrefix?: string;

  private readonly element = inject(ElementRef<HTMLElement>);
  private readonly scope = inject(GlowTourScope);
  private active: ActiveRootBinding | null = null;
  private initialized = false;

  ngOnChanges() {
    if (this.initialized) this.reconcile();
  }

  ngOnInit() {
    if (!this.tour) {
      throw new Error("GlowTourRoot requires a tour input.");
    }

    this.initialized = true;
    this.reconcile();
  }

  ngOnDestroy() {
    this.release();
  }

  private reconcile() {
    const root = this.element.nativeElement;
    const tour = this.tour;
    const idPrefix = this.idPrefix;
    this.scope.tour.set(tour);
    const current = this.active;
    if (
      current !== null &&
      current.root === root &&
      current.tour === tour &&
      current.idPrefix === idPrefix
    ) {
      return;
    }
    this.release();
    const binding = connectGlowTourRoot(tour, {
      idPrefix,
      root,
    });
    const active = { binding, idPrefix, root, tour };
    this.active = active;
    this.scope.binding.set(binding);
  }

  private release() {
    const active = this.active;
    if (!active) return;
    this.active = null;
    active.binding.release();
    if (this.scope.binding() === active.binding) this.scope.binding.set(null);
  }
}

@Component({
  selector: "glow-tour-header",
  standalone: true,
  imports: [NgTemplateOutlet],
  template: `
    @if (titled()) {
      <header data-glow-tour-header [class]="stepClass('header')" [id]="scope.binding()?.ids?.title">
        @if (titleTemplate()) {
          <ng-container [ngTemplateOutlet]="titleTemplate()" />
        } @else {
          {{ titleText() }}
        }
      </header>
    }
  `,
})
/** Header component displaying the current step's title. */
export class GlowTourHeader extends GlowTourReactiveComponent {
  readonly titled = computed(() => {
    const step = this.step();
    return !step || step.title != null;
  });
  readonly titleTemplate = computed(() => {
    const title = this.step()?.title;
    return title instanceof TemplateRef ? title : null;
  });
  readonly titleText = computed(() => {
    const title = this.step()?.title;
    return typeof title === "string" ? title : "";
  });
}

@Component({
  selector: "glow-tour-content",
  standalone: true,
  imports: [NgTemplateOutlet],
  template: `
    <div aria-live="polite" data-glow-tour-content [class]="stepClass('content')" [id]="scope.binding()?.ids?.description">
      @if (contentTemplate()) {
        <ng-container [ngTemplateOutlet]="contentTemplate()" />
      } @else {
        {{ contentText() }}
      }
    </div>
  `,
})
/** Content component displaying the current step's content with live region. */
export class GlowTourContent extends GlowTourReactiveComponent {
  readonly contentTemplate = computed(() => {
    const content = this.step()?.content;
    return content instanceof TemplateRef ? content : null;
  });
  readonly contentText = computed(() => {
    const content = this.step()?.content;
    return typeof content === "string" ? content : "";
  });
}

@Component({
  selector: "glow-tour-footer",
  standalone: true,
  template: `<footer data-glow-tour-footer [class]="stepClass('footer')"><ng-content /></footer>`,
})
/** Footer component containing action buttons. */
export class GlowTourFooter extends GlowTourReactiveComponent {}

@Directive()
abstract class GlowTourBoundElement<T extends Element> {
  protected readonly scope = useTourScope();
  /** The classes the current step adds to the `slot` component. */
  protected stepClass(slot: keyof TourClassNames) {
    return joinStepClass(this.scope.state(), slot);
  }
  private readonly destroyRef = inject(DestroyRef);
  private readonly injector = inject(Injector);

  protected bind(element: T, bindElement: (binding: AdapterRootBinding, element: T) => () => void) {
    const cleanup = effect(
      (onCleanup) => {
        const binding = this.scope.binding();
        if (binding) onCleanup(bindElement(binding, element));
      },
      { injector: this.injector },
    );
    this.destroyRef.onDestroy(() => cleanup.destroy());
  }
}

@Component({
  selector: "glow-tour-popover",
  standalone: true,
  // The idle attributes/style come from imported `@glowhop/core-tour/adapter`
  // constants, so ngc's AOT template analyzer (NG1010) cannot inline them as
  // string-interpolated literals in the template. Bound via component fields
  // instead; the values are still static, so server and client render
  // byte-identical output.
  template: `
    <section #tourElement
      [attr.aria-hidden]="idleAriaHidden"
      data-glow-tour-popover
      [class]="stepClass('popover')"
      [attr.aria-describedby]="titled() ? scope.binding()?.ids?.description : null"
      [attr.aria-labelledby]="titled() ? scope.binding()?.ids?.title : scope.binding()?.ids?.description"
      [id]="scope.binding()?.ids?.popover"
      [attr.inert]="idleInert"
      role="dialog"
      [style]="idleStyle"
      tabindex="-1"
    ><ng-content /></section>
  `,
})
/** Popover component containing the tour content with accessibility attributes. */
export class GlowTourPopover extends GlowTourBoundElement<HTMLElement> implements OnInit {
  @ViewChild("tourElement", { static: true }) private readonly element!: ElementRef<HTMLElement>;
  protected readonly idleAriaHidden = POPOVER_IDLE_ATTRIBUTES["aria-hidden"];
  protected readonly idleInert = POPOVER_IDLE_ATTRIBUTES.inert;
  protected readonly idleStyle = POPOVER_IDLE_STYLE_TEXT;
  // Without a title, the content names the dialog instead of describing it.
  protected readonly titled = computed(() => {
    const step = this.scope.state()?.currentStep?.currentProps;
    return !step || step.title != null;
  });

  ngOnInit() {
    this.bind(this.element.nativeElement, (binding, element) => binding.bindPopover(element));
  }
}

@Component({
  selector: "glow-tour-pointer",
  standalone: true,
  imports: [NgTemplateOutlet],
  template: `
    <div #tourElement data-glow-tour-pointer [class]="stepClass('pointer')" [attr.aria-hidden]="idleAriaHidden" [style]="idleStyle">
      @for (direction of directions; track direction) {
        <div [attr.data-glow-tour-pointer-direction]="direction">
          @if (asTemplate(content()[direction]); as template) {
            <ng-container [ngTemplateOutlet]="template" />
          } @else {
            {{ content()[direction] }}
          }
        </div>
      }
    </div>
  `,
})
/** Pointer component displaying directional indicators pointing to the target element. */
export class GlowTourPointer extends GlowTourBoundElement<HTMLElement> implements OnInit {
  @ViewChild("tourElement", { static: true }) private readonly element!: ElementRef<HTMLElement>;
  private readonly directionContentValue = signal<PointerDirectionContent | undefined>(undefined);
  protected readonly idleAriaHidden = POINTER_IDLE_ATTRIBUTES["aria-hidden"];
  protected readonly idleStyle = POINTER_IDLE_STYLE_TEXT;

  protected readonly directions = POINTER_DIRECTIONS;
  readonly content = computed(() => ({
    ...DEFAULT_POINTER_DIRECTION_CONTENT,
    ...this.directionContentValue(),
  }));

  /** Optional custom content for each pointer direction. */
  @Input() set directionContent(value: PointerDirectionContent | undefined) {
    this.directionContentValue.set(value);
  }

  protected asTemplate(value: PointerDirectionValue): TemplateRef<unknown> | null {
    return value instanceof TemplateRef ? value : null;
  }

  ngOnInit() {
    this.bind(this.element.nativeElement, (binding, element) => binding.bindPointer(element));
  }
}

@Component({
  selector: "glow-tour-overlay",
  standalone: true,
  template: `
    <svg #tourElement
      [attr.aria-hidden]="idleAriaHidden"
      [attr.data-glow-tour-allow-interaction]="idleAllowInteraction"
      data-glow-tour-overlay
      [class]="stepClass('overlay')"
      focusable="false"
      [attr.inert]="idleInert"
      [attr.preserveAspectRatio]="idlePreserveAspectRatio"
      role="presentation"
      [style]="idleStyle"
      viewBox="0 0 0 0"
    >
      <path
        [attr.cursor]="idlePathCursor"
        data-glow-tour-overlay-path
        fill-rule="evenodd"
        [attr.opacity]="idlePathOpacity"
        [attr.pointer-events]="idlePathPointerEvents"
      /><ng-content />
    </svg>
  `,
})
/** Overlay component rendering a clipped SVG mask highlighting the target element. */
export class GlowTourOverlay extends GlowTourBoundElement<SVGSVGElement> implements OnInit {
  @ViewChild("tourElement", { static: true }) private readonly element!: ElementRef<SVGSVGElement>;
  protected readonly idleAriaHidden = OVERLAY_IDLE_ATTRIBUTES["aria-hidden"];
  protected readonly idleAllowInteraction =
    OVERLAY_IDLE_ATTRIBUTES["data-glow-tour-allow-interaction"];
  protected readonly idleInert = OVERLAY_IDLE_ATTRIBUTES.inert;
  protected readonly idlePreserveAspectRatio = OVERLAY_IDLE_ATTRIBUTES.preserveAspectRatio;
  protected readonly idleStyle = OVERLAY_IDLE_STYLE_TEXT;
  protected readonly idlePathCursor = OVERLAY_PATH_IDLE_ATTRIBUTES.cursor;
  protected readonly idlePathOpacity = OVERLAY_PATH_IDLE_ATTRIBUTES.opacity;
  protected readonly idlePathPointerEvents = OVERLAY_PATH_IDLE_ATTRIBUTES["pointer-events"];

  ngOnInit() {
    this.bind(this.element.nativeElement, (binding, element) => binding.bindOverlay(element));
  }
}

@Directive()
abstract class GlowTourTrigger extends GlowTourReactiveComponent {
  private readonly ariaLabelValue = signal<string | undefined>(undefined);
  private readonly disabledValue = signal(false);

  protected readonly ariaLabelText = computed(() => this.ariaLabelValue());
  protected readonly consumerDisabled = computed(() => this.disabledValue());
  protected readonly ariaControls = computed(() => this.scope.binding()?.ids.popover);

  protected setAriaLabel(value: string | undefined) {
    this.ariaLabelValue.set(value);
  }

  protected setDisabled(value: boolean) {
    this.disabledValue.set(value);
  }

  /**
   * Tour state only disables a trigger while the tour is active, as in the vanilla adapter. During
   * a step transition the controller reports every command as unavailable; natively disabling the
   * focused trigger then would blur it, and screen readers lose their place in the dialog.
   */
  protected unavailableWhileActive(unavailable: boolean) {
    return this.snapshot()?.status === "active" && unavailable;
  }
}

@Component({
  selector: "glow-tour-previous-trigger",
  standalone: true,
  template: `
    <button
      data-glow-tour-previous-trigger
      [class]="stepClass('previous')"
      [attr.aria-controls]="ariaControls()"
      [attr.aria-disabled]="isDisabled() ? 'true' : 'false'"
      [attr.aria-label]="ariaLabelText() ?? label()"
      [attr.data-glow-tour-consumer-disabled]="consumerDisabled() ? 'true' : null"
      [disabled]="isDisabled()"
      type="button"
    ><ng-content>{{ label() }}</ng-content></button>
  `,
})
/** Button component for navigating to the previous step in the tour. */
export class GlowTourPreviousTrigger extends GlowTourTrigger {
  private readonly previousLabelValue = signal<string | undefined>(undefined);

  /** Optional aria-label for the back button. */
  @Input() set ariaLabel(value: string | undefined) {
    this.setAriaLabel(value);
  }
  /** Optional label text for the back button. */
  @Input() set previousLabel(value: string | undefined) {
    this.previousLabelValue.set(value);
  }
  /** Whether the button is disabled. */
  @Input({ transform: booleanAttribute }) set disabled(value: boolean) {
    this.setDisabled(value);
  }

  readonly isDisabled = computed(
    () =>
      this.consumerDisabled() ||
      this.unavailableWhileActive(!this.snapshot()?.canPrevious) ||
      this.step()?.controls?.previous?.state === "disabled",
  );
  readonly label = computed(() => this.previousLabelValue() ?? "Previous step");
}

@Component({
  selector: "glow-tour-advance-trigger",
  standalone: true,
  template: `
    <button
      data-glow-tour-advance-trigger
      [class]="stepClass('advance')"
      [attr.aria-controls]="ariaControls()"
      [attr.aria-disabled]="isDisabled() ? 'true' : 'false'"
      [attr.aria-label]="ariaLabelText() ?? label()"
      [attr.data-glow-tour-consumer-disabled]="consumerDisabled() ? 'true' : null"
      [disabled]="isDisabled()"
      type="button"
    ><ng-content>{{ label() }}</ng-content></button>
  `,
})
/** Button component for advancing to the next step or finishing the tour. */
export class GlowTourAdvanceTrigger extends GlowTourTrigger {
  private readonly finishLabelValue = signal<string | undefined>(undefined);
  private readonly advanceLabelValue = signal<string | undefined>(undefined);

  /** Optional aria-label for the advance button. */
  @Input() set ariaLabel(value: string | undefined) {
    this.setAriaLabel(value);
  }
  /** Whether the button is disabled. */
  @Input({ transform: booleanAttribute }) set disabled(value: boolean) {
    this.setDisabled(value);
  }
  /** Optional label text for the finish step. */
  @Input() set finishLabel(value: string | undefined) {
    this.finishLabelValue.set(value);
  }
  /** Optional label text for advancing to the next step. */
  @Input() set advanceLabel(value: string | undefined) {
    this.advanceLabelValue.set(value);
  }

  readonly isDisabled = computed(
    () =>
      this.consumerDisabled() ||
      this.unavailableWhileActive(!this.snapshot()?.canAdvance) ||
      this.step()?.controls?.advance?.state === "disabled",
  );
  readonly label = computed(() => {
    return this.snapshot()?.isLastStep
      ? (this.finishLabelValue() ?? "Finish tour")
      : (this.advanceLabelValue() ?? "Advance step");
  });
}

@Component({
  selector: "glow-tour-cancel-trigger",
  standalone: true,
  template: `
    <button
      data-glow-tour-cancel-trigger
      [class]="stepClass('cancel')"
      [attr.aria-controls]="ariaControls()"
      [attr.aria-disabled]="isDisabled() ? 'true' : 'false'"
      [attr.aria-label]="ariaLabelText() ?? label()"
      [attr.data-glow-tour-consumer-disabled]="consumerDisabled() ? 'true' : null"
      [disabled]="isDisabled()"
      type="button"
    ><ng-content>{{ label() }}</ng-content></button>
  `,
})
/** Button component for canceling/skipping the tour. */
export class GlowTourCancelTrigger extends GlowTourTrigger {
  private readonly cancelLabelValue = signal<string | undefined>(undefined);

  /** Optional aria-label for the cancel button. */
  @Input() set ariaLabel(value: string | undefined) {
    this.setAriaLabel(value);
  }
  /** Whether the button is disabled. */
  @Input({ transform: booleanAttribute }) set disabled(value: boolean) {
    this.setDisabled(value);
  }
  /** Optional label text for the cancel button. */
  @Input() set cancelLabel(value: string | undefined) {
    this.cancelLabelValue.set(value);
  }

  readonly isDisabled = computed(
    () =>
      this.consumerDisabled() ||
      this.unavailableWhileActive(!this.snapshot()?.canCancel) ||
      this.step()?.controls?.cancel?.state === "disabled",
  );
  readonly label = computed(() => this.cancelLabelValue() ?? "Skip");
}
